### ISSUE TITLE
support multiple workers

### ISSUE THREAD

**Issue by hostalp** [kube-logging/fluent-plugin-tag-normaliser#4]
**Is your feature request related to a problem? Please describe.**
When attempting to use tag_normaliser with workers>1 I receive:
`error="Plugin 'tag_normaliser' does not support multi workers configuration (Fluent::Plugin::TagNormaliserOutput)`

**Describe the solution you'd like to see**
Would it be possible to implement the multi-worker support?

**Describe alternatives you've considered**
Probably the only workaround is to use multiple replicas instead.

**Comment by Drupi** [comment]
Bumping! Also interested in that feature

**Comment by Drupi** [comment]
I'm metntioning that also here: https://github.com/banzaicloud/logging-operator/issues/1159

**Comment by pepov** [comment]
this is already fixed with the latest release. From a fluentd container created by logging-operator version 4.0.0
```
/ $ gem list | grep tag-normaliser
fluent-plugin-tag-normaliser (0.1.2)
```
